# Generated by Django 2.2.dev20181210142849 on 2018-12-12 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mynotes',
            old_name='pub_date',
            new_name='note_created_date',
        ),
    ]
