# Generated by Django 2.2.dev20181210142849 on 2018-12-13 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_auto_20181212_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mynotes',
            name='description',
            field=models.TextField(max_length=300),
        ),
        migrations.AlterField(
            model_name='mynotes',
            name='title',
            field=models.CharField(max_length=60),
        ),
    ]
