# Generated by Django 2.2.dev20181210142849 on 2018-12-27 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0003_auto_20181213_0941'),
    ]

    operations = [
        migrations.AddField(
            model_name='mynotes',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='mynotes',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
